[package]
name = "fadia-patchersdk-server"
edition = "2024"
version.workspace = true

[dependencies]
tokio.workspace = true
axum.workspace = true
tower-http.workspace = true

serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

common.workspace = true
